### ISSUE TITLE
hook的时候出现异常，两种hook都出现问题hook-epic

### ISSUE THREAD

**Issue by bigjelly** [XanderWang/performance#8]
Caused by: java.lang.RuntimeException: API LEVEL: 32 is not supported now : (
                                                                                                    	at me.weishu.epic.art.method.Offset.initFields(Offset.java:165)
                                                                                                    	at me.weishu.epic.art.method.Offset.<clinit>(Offset.java:53)
                                                                                                    	at me.weishu.epic.art.method.ArtMethod.getEntryPointFromQuickCompiledCode(ArtMethod.java:404) 
                                                                                                    	at me.weishu.epic.art.Epic.hookMethod(Epic.java:105) 
                                                                                                    	at me.weishu.epic.art.Epic.hookMethod(Epic.java:75) 
                                                                                                    	at de.robv.android.xposed.DexposedBridge.hookMethod(DexposedBridge.java:124) 
                                                                                                    	at io.github.xanderwang.hook.epic.EpicBridge.hookMethod(EpicBridge.java:41) 
                                                                                                    	at io.github.xanderwang.hook.HookBridge.hookMethod(HookBridge.java:146) 
                                                                                                    	at io.github.xanderwang.performance.ThreadTool.hookThread(ThreadTool.java:366) 
                                                                                                    	at io.github.xanderwang.performance.ThreadTool.init(ThreadTool.java:356) 
                                                                                                    	at io.github.xanderwang.performance.PERF.init(PERF.java:195) 
                                                                                                    	at io.github.xanderwang.performance.demo.KotlinApplication.initPERF(KotlinApplication.kt:20) 
                                                                                                    	at io.github.xanderwang.performance.demo.KotlinApplication.onCreate(KotlinApplication.kt:12) 
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1223) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6906) 
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:266) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:233) 
                                                                                                    	at android.os.Looper.loop(Looper.java:335) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8023) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by justintravisegfw** [comment]
The error indicates that the library you are using does not support API level 32; consider downgrading to a supported version or using an updated version of the library that includes support for API level 32.

**Comment by K5BySaUdTH4K** [comment]
Have you checked if the `Offset.java` class or the library version you're using can be updated to better support API level 32, as the current exception indicates a limitation in the `initFields` method?

**Comment by Fi6uDvGWucFv** [comment]
It looks like the `Offset.initFields` method is specifically failing due to the unsupported API level 32. Have you verified if there are any known workarounds or alternate versions of the Epic library that might address this compatibility issue?
